USE isogjdb;

INSERT INTO isogjdb.city (name) VALUES ('Minsk');
INSERT INTO isogjdb.city (name) VALUES ('Brest');
INSERT INTO isogjdb.type_of_accepted (name_of_accepted) VALUES ('Accept');
INSERT INTO isogjdb.type_of_accepted (name_of_accepted) VALUES ('Not');
INSERT INTO isogjdb.type_of_education (name_type_of_education) VALUES ('High education');
INSERT INTO isogjdb.type_of_education (name_type_of_education) VALUES ('School education');
INSERT INTO isogjdb.type_of_skill (name_of_type_skill) VALUES ('Practical');
INSERT INTO isogjdb.type_of_skill (name_of_type_skill) VALUES ('Theoretical');
INSERT INTO isogjdb.type_of_task (name_type_of_task) VALUES ('Sum type of task');
INSERT INTO isogjdb.type_of_user (name_of_type_user) VALUES ('User');
INSERT INTO isogjdb.type_of_user (name_of_type_user) VALUES ('Company');
INSERT INTO isogjdb.type_of_user (name_of_type_user) VALUES ('Admin');
INSERT INTO isogjdb.type_of_vacancy (name_type_of_vacancy) VALUES ('Dba');
INSERT INTO isogjdb.type_of_vacancy (name_type_of_vacancy) VALUES ('Frontend');
INSERT INTO isogjdb.company (date_of_creation_company, info_of_company, name_of_company, city_of_company) VALUES ('2014-11-14 16:30:18', 'Bsuir company', 'Bsuir', 1);
INSERT INTO isogjdb.gender (name_od_gender) VALUES ('Male');
INSERT INTO isogjdb.gender (name_od_gender) VALUES ('Female');
INSERT INTO isogjdb.position (name_of_position) VALUES ('Junior');
INSERT INTO isogjdb.position (name_of_position) VALUES ('Senior');
INSERT INTO isogjdb.position (name_of_position) VALUES ('Junior');
INSERT INTO isogjdb.position (name_of_position) VALUES ('Senior');
INSERT INTO isogjdb.school (name_of_school, city) VALUES ('Number 6', 1);
INSERT INTO isogjdb.skill (name_of_skill, type_of_skill) VALUES ('Model', 2);
INSERT INTO isogjdb.task (info_of_task, name_of_task, type_of_task) VALUES ('Do frontend', 'Front', 1);
INSERT INTO isogjdb.university (name_of_university, city) VALUES ('BSUIR', 1);
INSERT INTO isogjdb.faculty (name_of_faculty, university) VALUES ('Poit', 1);
INSERT INTO isogjdb.user (active, email, user_name, user_patronymic, user_surname, city_of_living, gender, type_of_user) VALUES (1, 'Vad@bsuir.by', 'Vadim', 'Mikalaevich', 'Vidnichuk', 1, 1, 3);
INSERT INTO isogjdb.user (active, email, user_name, user_patronymic, user_surname, city_of_living, gender, type_of_user) VALUES (1, 'User@Bsuir.by', 'User', 'Userovich', 'Userchuk', 1, 1, 1);
INSERT INTO isogjdb.user (active, email, user_name, user_patronymic, user_surname, city_of_living, gender, type_of_user) VALUES (1, 'Company', 'Company', 'Company', 'Company', 1, 1, 2);
INSERT INTO isogjdb.my_user_credentials (user_login, user_password, user) VALUES ('Admin', 'c1c224b03cd9bc7b6a86d77f5dace40191766c485cd55dc48caf9ac873335d6f', 1);
INSERT INTO isogjdb.my_user_credentials (user_login, user_password, user) VALUES ('User', 'b512d97e7cbf97c273e4db073bbb547aa65a84589227f8f3d9e4a72b9372a24d', 2);
INSERT INTO isogjdb.my_user_credentials (user_login, user_password, user) VALUES ('Company', 'de4743c879734dc38cb3e270ecefcae077c3c2e626f9298115d5a03c8613f89b', 3);
INSERT INTO isogjdb.user_city_to_work (city, user) VALUES (1, 1);
INSERT INTO isogjdb.user_company (company, position, user) VALUES (1, 1, 1);
INSERT INTO isogjdb.user_skill (skill_mark, skill_practical_mark, id_marker, id_skill, id_user) VALUES ('6', '7', 2, 1, 1);
INSERT INTO isogjdb.vacancy (info_of_vacancy, task, type_of_vacancy) VALUES ('Do work', 1, 1);
INSERT INTO isogjdb.vacancy_skill (skill, vacancy) VALUES (1, 1);
INSERT INTO isogjdb.vacancy_user (if_user_accepted, if_company_accepted, user, vacancy) VALUES (2, 2, 1, 1);
INSERT INTO isogjdb.education (end_of_education, start_of_education, faculty, school, type_of_education, user) VALUES ('2014-11-14 16:38:39', '2017-11-14 16:38:42', 1, null, 1, 1);
INSERT INTO isogjdb.experience (date_of_end, date_of_start, prev_company, user) VALUES ('2015-11-14 16:39:36', '2017-11-14 16:39:38', 1, 1);
INSERT INTO isogjdb.summary (text_of_summary, user) VALUES ('Good user summary', 1);